<?php
/**
 * Created by PhpStorm.
 * User: F1083
 * Date: 2018/12/26
 * Time: 8:51
 */

class PostController extends Controller
{
    function missingAction($actionID)
    {
        //parent::missingAction($actionID); // TODO: Change the autogenerated stub
        echo $actionID;

    }

    function actionsave()
    {
//        $post = new Post();
//        $post->title = "semiconductor1";
//        $post->keyword = "pi1n";
//        $post->addTime = time();
//        echo $post->save();

        //no support
        echo (new Post())->insert([
            'title'=>'lufei',
            'keyword'=>'lu',
            'addTime'=>new CDbExpression('NOW()')
        ]);
    }

    function actionfind()
    {
//        $data = Post::model()->find();
//        $data = (new Post())->find();
//        $data = (new Post())->find("id=2");
//        $data = (new Post())->find("id=:id",['id'=>1]);
        //no support
//        $data = (new Post())->find(['in','id',[1]]);
//        $data = (new Post())->findByPk(1);
//        $data = (new Post())->findByPk(1,'title="semiconductor"');
//        $data = (new Post())->findByPk(1,'title=:title',['title'=>'semiconductor']);
//        $data = (new Post())->findByAttributes(['title'=>'spider'],'id=2');
//        $data = (new Post())->findByAttributes(['title'=>'spider'],'id=:id',['id'=>2]);
//        $data = (new Post())->findBySql("select * from post where id=:id",['id'=>1]);
//        $data = (new Post())->findAll();

        $criteria            = new CDbCriteria();
        $criteria->select    = "id,title";
        $criteria->condition = "id=:id";
        $criteria->params    = ['id'=>1];
        $data = (new Post())->find($criteria);
        print_r($data->title);
    }

    function actionUpdate()
    {
//        $post = Post::model()->findByAttributes(['title'=>'semiconductor'],'id=:id',['id'=>1]);
//
//        $post = (new Post())->findByPk(1);
//        $post->title = "criteria";
//        echo $post->save();

//        echo Post::model()->updateAll([
////            'title'=>'japanese'
////        ],'id=:id',['id'=>1]);
///
//          echo Post::model()->updateByPk(1,['title'=>'seeder'],'id=:id',['id'=>1]);
//        echo Post::model()->updateCounters(['addTime'=>2],'id=:id',['id'=>1]);

        echo (new Post())->updateCounters(['title'=>3],'id=2');
    }

    function actiondelete()
    {
//        echo (new Post())->findByPk(2)->delete();
//        echo (new Post())->deleteAll('id=:id and title=:title',['id'=>1,'title'=>'seeder']);

        echo (new Post())->deleteAllByAttributes(['title'=>'a']);
    }

    function actiontransaction()
    {

        $post = Post::model();
        $transaction = $post->dbConnection->beginTransaction();
        try{

            $post1 = new Post();
            $post1->title = "test";
            $post1->save();

            echo $post->findByPk(10)->title;

            echo $transaction->commit();
        }catch (Exception $exception){
            echo $transaction->rollback();
        }
    }



    function actionbeforedelete1()
    {
//        echo (new Post())->deleteAll('id=:id',['id'=>11]);

        echo json_encode((new Post())->published()->recently()->findAll());
    }

    function actionyii()
    {

    }
}