<?php
/**
 * Created by PhpStorm.
 * User: F1083
 * Date: 2018/12/26
 * Time: 8:48
 */

class Post extends CActiveRecord
{
    public function tableName()
    {
        //return parent::tableName(); // TODO: Change the autogenerated stub
        return "tpl_post";
    }

    public function primaryKey()
    {
        //parent::primaryKey(); // TODO: Change the autogenerated stub
        return 'id';
    }

    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }

    protected function beforeDelete()
    {
        return parent::beforeDelete(); // TODO: Change the autogenerated stub



    }
    function relations()
    {
        //return parent::relations(); // TODO: Change the autogenerated stub
        //变量名 关系类型  关系表 关联字段
        return [
            'author'=>[self::BELONGS_TO,'User','author_id'],
            'categories'=>[self::MANY_MANY,'Category','tpl_post_category(post_id,category_id)']
        ];
    }

    function scopes()
    {
        //return parent::scopes(); // TODO: Change the autogenerated stub
        return [
            'published'=>[
                'condition'=>''
            ],
            'recently'=>[
                'order'=>'id desc'
            ]
        ];
    }
}