<?php
/**
 * Created by PhpStorm.
 * User: F1083
 * Date: 2018/12/25
 * Time: 16:14
 */
class Test extends CActiveRecord
{
    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }

    public function tableName()
    {
        //return parent::tableName(); // TODO: Change the autogenerated stub
        return "test";
    }

    public function primaryKey()
    {
        //parent::primaryKey(); // TODO: Change the autogenerated stub
        return 'id';
    }

    public $name = "monkey";


    public static function getTests()
    {
        return self::$db->createCommand()
            ->select("*")
            ->from("test")
            ->where(['in','id',[1,2,3]])
            ->queryAll();
    }
}