<?php
/**
 * Created by PhpStorm.
 * User: F1083
 * Date: 2018/12/25
 * Time: 12:41
 */
class AddAction extends CAction
{
    public function run()
    {
        //parent::run(); // TODO: Change the autogenerated stub
        echo 'nihao';
    }
}